-- SQL query to add new pincodes and areas
-- Note: Using Postgres gen_random_uuid() for IDs as seen in coimbatore_pincodes.sql

INSERT INTO "ServiceArea" ("id", "areaName", "pincode", "active", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Town Hall', '641001', true, NOW(), NOW()),
  (gen_random_uuid(), 'R. S. Puram', '641002', true, NOW(), NOW()),
  (gen_random_uuid(), 'Idigarai', '641022', true, NOW(), NOW()),
  (gen_random_uuid(), 'Edayarpalayam', '641025', true, NOW(), NOW()),
  (gen_random_uuid(), 'Arisipalayam', '641032', true, NOW(), NOW()),
  (gen_random_uuid(), 'Saibaba Colony', '641043', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ramanathapuram', '641045', true, NOW(), NOW()),
  (gen_random_uuid(), 'Bharathiyar University', '641046', true, NOW(), NOW()),
  (gen_random_uuid(), 'Pappampatti', '641103', true, NOW(), NOW()),
  (gen_random_uuid(), 'Rasipalayam', '641402', true, NOW(), NOW()),
  (gen_random_uuid(), 'Annur-Mettupalayam', '641653', true, NOW(), NOW()),
  (gen_random_uuid(), 'Alathur', '641655', true, NOW(), NOW()),
  (gen_random_uuid(), 'K.Ayyampalayam', '641662', true, NOW(), NOW()),
  (gen_random_uuid(), 'Alagumalai', '641665', true, NOW(), NOW()),
  (gen_random_uuid(), 'Devanampalayam', '641667', true, NOW(), NOW()),
  (gen_random_uuid(), 'Karavalimadapur', '641668', true, NOW(), NOW()),
  (gen_random_uuid(), 'Achipatti', '642002', true, NOW(), NOW()),
  (gen_random_uuid(), 'Akilandapuram', '642004', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kambalapatti', '642007', true, NOW(), NOW()),
  (gen_random_uuid(), 'Anaimalai', '642104', true, NOW(), NOW()),
  (gen_random_uuid(), 'Lawley Road', '641003', true, NOW(), NOW()),
  (gen_random_uuid(), 'Gandhinagar', '642154', true, NOW(), NOW()),
  (gen_random_uuid(), 'Peelamedu', '641004', true, NOW(), NOW()),
  (gen_random_uuid(), 'Singanallur', '641005', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ganapathy', '641006', true, NOW(), NOW()),
  (gen_random_uuid(), 'Seeranayakenpalayam', '641007', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ukkadam', '641008', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ramnagar', '641009', true, NOW(), NOW()),
  (gen_random_uuid(), 'Perur', '641010', true, NOW(), NOW()),
  (gen_random_uuid(), 'NSR Road', '641011', true, NOW(), NOW()),
  (gen_random_uuid(), 'Gandipuram', '641012', true, NOW(), NOW()),
  (gen_random_uuid(), 'GCT', '641013', true, NOW(), NOW()),
  (gen_random_uuid(), 'Civil Aero Post', '641014', true, NOW(), NOW()),
  (gen_random_uuid(), 'Uppilipalayam', '641015', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ondipudur Post', '641016', true, NOW(), NOW()),
  (gen_random_uuid(), 'Thoppampatti', '641017', true, NOW(), NOW()),
  (gen_random_uuid(), 'Racecourse', '641018', true, NOW(), NOW()),
  (gen_random_uuid(), 'Periyanayaken Palayam', '641020', true, NOW(), NOW()),
  (gen_random_uuid(), 'Echanari', '641021', true, NOW(), NOW()),
  (gen_random_uuid(), 'Podanur', '641023', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sundarapuram', '641024', true, NOW(), NOW()),
  (gen_random_uuid(), 'Selvapuram', '641026', true, NOW(), NOW()),
  (gen_random_uuid(), 'Rathnapuri', '641027', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sowripalayam', '641028', true, NOW(), NOW()),
  (gen_random_uuid(), 'G N Mills', '641029', true, NOW(), NOW()),
  (gen_random_uuid(), 'Koundan Palayam', '641030', true, NOW(), NOW()),
  (gen_random_uuid(), 'NSN Palayam', '641031', true, NOW(), NOW()),
  (gen_random_uuid(), 'Neelikonampalayam', '641033', true, NOW(), NOW()),
  (gen_random_uuid(), 'Tudiyalur', '641034', true, NOW(), NOW()),
  (gen_random_uuid(), 'Saravanampatti', '641035', true, NOW(), NOW()),
  (gen_random_uuid(), 'Najundapuram', '641036', true, NOW(), NOW()),
  (gen_random_uuid(), 'Papanayakenpalayam', '641037', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kuppakonanpudur', '641038', true, NOW(), NOW()),
  (gen_random_uuid(), 'Thelungupalayam', '641039', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vadavalli', '641041', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kovaipudur', '641042', true, NOW(), NOW()),
  (gen_random_uuid(), 'Siddhapudur', '641044', true, NOW(), NOW()),
  (gen_random_uuid(), 'Jothipuram', '641047', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vellanaipatti', '641048', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chinnavedampatti', '641049', true, NOW(), NOW()),
  (gen_random_uuid(), 'Malumichampatti', '641050', true, NOW(), NOW()),
  (gen_random_uuid(), 'Neelambur', '641062', true, NOW(), NOW()),
  (gen_random_uuid(), 'Alandurai', '641101', true, NOW(), NOW()),
  (gen_random_uuid(), 'Bodipalayam', '641105', true, NOW(), NOW()),
  (gen_random_uuid(), 'Anaikatti', '641108', true, NOW(), NOW()),
  (gen_random_uuid(), 'Deenampalayam', '641109', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vellalapalayam Podanur', '641111', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ettimadai', '641112', true, NOW(), NOW()),
  (gen_random_uuid(), 'Karunya', '641114', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chettipalayam', '641201', true, NOW(), NOW()),
  (gen_random_uuid(), 'Caltonpet / Kangeyam Palayam', '641401', true, NOW(), NOW()),
  (gen_random_uuid(), 'Muthugoundanpudur', '641406', true, NOW(), NOW()),
  (gen_random_uuid(), 'Arasur', '641407', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chennappachettipudur', '641659', true, NOW(), NOW())
ON CONFLICT ("pincode") DO NOTHING;
