-- Insert all Coimbatore pincodes without duplicates
-- Using ON CONFLICT to skip duplicates based on unique pincode and areaName constraints

INSERT INTO "ServiceArea" ("id", "areaName", "pincode", "active", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Coimbatore Central', '641001', true, NOW(), NOW()),
  (gen_random_uuid(), 'RS Puram', '641002', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sai Baba Colony', '641011', true, NOW(), NOW()),
  (gen_random_uuid(), 'Gandhipuram', '641012', true, NOW(), NOW()),
  (gen_random_uuid(), 'Peelamedu', '641004', true, NOW(), NOW()),
  (gen_random_uuid(), 'Race Course', '641018', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ganapathy', '641006', true, NOW(), NOW()),
  (gen_random_uuid(), 'Singanallur', '641005', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kuniyamuthur', '641008', true, NOW(), NOW()),
  (gen_random_uuid(), 'Saravanampatti', '641035', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vadavalli', '641041', true, NOW(), NOW()),
  (gen_random_uuid(), 'Podanur', '641023', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kavundampalayam', '641030', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sulur', '641402', true, NOW(), NOW()),
  (gen_random_uuid(), 'Thudiyalur', '641034', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vellalore', '641111', true, NOW(), NOW()),
  (gen_random_uuid(), 'Karamadai', '641104', true, NOW(), NOW()),
  (gen_random_uuid(), 'Mettupalayam', '641301', true, NOW(), NOW()),
  (gen_random_uuid(), 'Pollachi', '642001', true, NOW(), NOW()),
  (gen_random_uuid(), 'Valparai', '642127', true, NOW(), NOW()),
  (gen_random_uuid(), 'Annur', '641653', true, NOW(), NOW()),
  (gen_random_uuid(), 'Avinashi', '641654', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kinathukadavu', '642109', true, NOW(), NOW()),
  (gen_random_uuid(), 'Madukkarai', '641105', true, NOW(), NOW()),
  (gen_random_uuid(), 'Perur', '641010', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chettipalayam', '641201', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kalapatti', '641048', true, NOW(), NOW()),
  (gen_random_uuid(), 'Thondamuthur', '641109', true, NOW(), NOW()),
  (gen_random_uuid(), 'Anamalai', '642104', true, NOW(), NOW()),
  (gen_random_uuid(), 'Negamam', '642120', true, NOW(), NOW()),
  (gen_random_uuid(), 'Udumalpet', '642126', true, NOW(), NOW()),
  (gen_random_uuid(), 'Palladam', '641664', true, NOW(), NOW()),
  (gen_random_uuid(), 'Tiruppur Road', '641602', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ondipudur', '641016', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kurichi', '641021', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vilankurichi', '641036', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chinnavedampatti', '641049', true, NOW(), NOW()),
  (gen_random_uuid(), 'Vellakinar', '641025', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kovaipudur', '641042', true, NOW(), NOW()),
  (gen_random_uuid(), 'Neelambur', '641062', true, NOW(), NOW()),
  (gen_random_uuid(), 'Coimbatore North', '641009', true, NOW(), NOW()),
  (gen_random_uuid(), 'Coimbatore South', '641014', true, NOW(), NOW()),
  (gen_random_uuid(), 'Aerodrome', '641015', true, NOW(), NOW()),
  (gen_random_uuid(), 'Tidel Park', '641013', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ukkadam', '641007', true, NOW(), NOW()),
  (gen_random_uuid(), 'Town Hall', '641003', true, NOW(), NOW()),
  (gen_random_uuid(), 'Oppanakara Street', '641037', true, NOW(), NOW()),
  (gen_random_uuid(), 'Rathinapuri', '641027', true, NOW(), NOW()),
  (gen_random_uuid(), 'Selvapuram', '641026', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sundarapuram', '641024', true, NOW(), NOW()),
  (gen_random_uuid(), 'Velandipalayam', '641019', true, NOW(), NOW()),
  (gen_random_uuid(), 'Uppilipalayam', '641017', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ramanathapuram', '641045', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sowripalayam', '641028', true, NOW(), NOW()),
  (gen_random_uuid(), 'Hopes College', '641029', true, NOW(), NOW()),
  (gen_random_uuid(), 'Peelamedu Pudur', '641020', true, NOW(), NOW()),
  (gen_random_uuid(), 'Lakshmi Mills', '641032', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sivananda Colony', '641033', true, NOW(), NOW()),
  (gen_random_uuid(), 'Tatabad', '641038', true, NOW(), NOW()),
  (gen_random_uuid(), 'Bharathi Park', '641043', true, NOW(), NOW()),
  (gen_random_uuid(), 'Sitra', '641044', true, NOW(), NOW()),
  (gen_random_uuid(), 'Idigarai', '641022', true, NOW(), NOW()),
  (gen_random_uuid(), 'Koundampalayam', '641031', true, NOW(), NOW()),
  (gen_random_uuid(), 'Saravanampatty', '641039', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chinniyampalayam', '641040', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kanuvai', '641106', true, NOW(), NOW()),
  (gen_random_uuid(), 'Anaikatti', '641108', true, NOW(), NOW()),
  (gen_random_uuid(), 'Ettimadai', '641112', true, NOW(), NOW()),
  (gen_random_uuid(), 'Jothipuram', '641047', true, NOW(), NOW()),
  (gen_random_uuid(), 'Bharathiar University', '641046', true, NOW(), NOW()),
  (gen_random_uuid(), 'Chinnakkarai', '641050', true, NOW(), NOW()),
  (gen_random_uuid(), 'Irugur', '641103', true, NOW(), NOW()),
  (gen_random_uuid(), 'Kaniyur', '641659', true, NOW(), NOW()),
  (gen_random_uuid(), 'Narasimhanaickenpalayam', '641051', true, NOW(), NOW()),
  (gen_random_uuid(), 'Othakalmandapam', '641052', true, NOW(), NOW()),
  (gen_random_uuid(), 'Somayampalayam', '641107', true, NOW(), NOW()),
  (gen_random_uuid(), 'Thenkarai', '641687', true, NOW(), NOW()),
  (gen_random_uuid(), 'Theethipalayam', '641603', true, NOW(), NOW()),
  (gen_random_uuid(), 'Veerapandi', '641666', true, NOW(), NOW())
ON CONFLICT ("pincode") DO NOTHING;
