// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a direct (non-pooled) connection string for migrations.
    // In .env, set DIRECT_URL to the "Direct" connection string from Supabase.
    // You can still use DATABASE_URL for your application/client if you want pooling.
    url: env("DIRECT_URL"),
  },
});
